### Obtain JWT Token
POST http://localhost:8180/realms/water-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=water-app-client&client_secret=VNV3owmEPblLorj3KEELrJNnLyqiQRjC&username=captain_user&password=password&grant_type=password

> {% client.global.set("ACCESS_TOKEN", response.body.access_token) %}

### Create and Arrive at Dock Operation
POST http://localhost:8081/api/dock-operations/arrive
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "arrivalTime": "2023-10-01T10:00:00",
  "location": "Dock A",
  "vesselNumber": "V12345",
  "purchaseOrderNumbers": [
    "PO123456"
  ],
  "sellerId": "9ae35800-5fdf-4932-a713-251f49e11012"
}

### Leave Dock Operation
PUT http://localhost:8081/api/dock-operations/leave
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "vesselNumber": "V12345"
}